providers = ["node"]

[variables]
NIXPACKS_NODE_VERSION = "24"

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run db:migrate && npm run user:bootstrap && npm run start"
